### ISSUE TITLE
Type Hints error: ->addVisitThatExpiresAt( Carbon::now()->addHours(2) ); 

### ISSUE THREAD

**Issue by selfpaidinc** [cyrildewit/laravel-page-visits-counter#10]
When trying to use addVisitThatExpiresAt I get an exception error.

```
Argument 1 passed to Cyrildewit\PageVisitsCounter\Classes\SessionHistory::fromCamelCaseToDashes() must be an instance of Cyrildewit\PageVisitsCounter\Classes\string, string given
```

**Comment by cyrildewit** [comment]
Hi selfpaidinc,

First I want to thank you for reporting this issue.

I did a little research and found out why you are getting this error. I was type hinting a parameter of the function fromCamelCaseToDashes: `(string $value)`. But I didn't knew that type hints cannot be used with types such as **int** or **string**. 

Source: https://stackoverflow.com/questions/5724677/php-type-hinting-to-primitive-values

I will fix it and release a new version.

**Comment by selfpaidinc** [comment]
Thanks very much for the quick reply I will be sure to comment when it's fixed. Also, any plans on allowing to order model items by view count?

**Comment by cyrildewit** [comment]
I released  v0.1.5. So a `composer update` will install the new version.

Could you create another "issue" where you describe this missing feature. Because it has nothing to do with this "issue".
Because it doesn't have to do anything with this issue.

**Comment by selfpaidinc** [comment]
Ran update, issue resolved! Thanks for the super fast response.

**Comment by selfpaidinc** [comment]
Sorry, must not have looked into this completely. Below my page content there is another exception.


(1/1) InvalidArgumentExceptionUnknown setter 'date'
--
in Carbon.php (line 758)
at Carbon->__set('date', '2017-07-14 16:57:26.000000')
at DateTime->__sleep()
at serialize(array('_token' => 'ftaE4vKPtBORLyXhFH5HGmGJS6qtifjuXRjgBcBI', '_previous' => array('url' => 'http://www.**********.com/*****/****************'), '_flash' => array('old' => array(), 'new' => array()), 'page-visits-counter' =>array('history' => array('track' => array(array('visitable_id' => 3, 'expires_at' => object(Carbon)))))))in Store.php (line 129)
at Store->save()in StartSession.php (line 88)
at StartSession->terminate(object(Request), object(Response))in Kernel.php (line 218)
at Kernel->terminateMiddleware(object(Request), object(Response))in Kernel.php (line 189)
at Kernel->terminate(object(Request), object(Response))in index.php (line 58)

**Comment by cyrildewit** [comment]
Could you tell me which Laravel version you are using? and on which version of PHP you are running the application. It might be possible that it is not compatible.

**Comment by selfpaidinc** [comment]
I'm using Laravel 5.4 and HHVM

**Comment by cyrildewit** [comment]
Are you caching the model where you are calling the ->addVisitThatExpiresAt() function on?

**Comment by selfpaidinc** [comment]
I'm still developing so not caching anything yet.

**Comment by cyrildewit** [comment]
I don't think this has anything to do with Laravel Page Visits Counter. Can you maybe post a screenshot of the full error on the webpage and (if it's there) the error inside the `laravel.log` file that you can find inside the storage directory.

**Comment by selfpaidinc** [comment]
When I comment out $track->addVisitThatExpiresAt(Carbon::now()->addHours(3)); the error goes away.

![image](https://user-images.githubusercontent.com/18217404/28220457-7f534dba-688d-11e7-9995-4fad579d6c12.png)

```
[2017-07-14 16:09:28] local.ERROR: exception 'InvalidArgumentException' with message 'Unknown setter 'date'' in /var/www/clients/client1/web1/web/laravel/vendor/nesbot/carbon/src/Carbon/Carbon.php:758
Stack trace:
#0 (): Carbon\Carbon->__set()
#1 (): DateTime->__sleep()
#2 /var/www/clients/client1/web1/web/laravel/vendor/laravel/framework/src/Illuminate/Session/Store.php(129): serialize()
#3 /var/www/clients/client1/web1/web/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#4 /var/www/clients/client1/web1/web/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\Session\Middleware\StartSession->terminate()
#5 /var/www/clients/client1/web1/web/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware()
#6 /var/www/clients/client1/web1/web/laravel/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate()
#7 {main}  
```

**Comment by cyrildewit** [comment]
I'm sorry but I can't fix this. It has something to do with HHVM. I think when you upload your application to a real web server (like a droplet of DigitalOcean) it will work.

It seems that HHVM compiles php code differently than Apache or nginx.

Try it again by running the application with `php artisan serve`. This will use the original php.
